#!/usr/bin/python3

import rospy
import time
from actionlib_msgs.msg import GoalStatusArray
from playsound import playsound

audio = 'speech.mp3'
audio1 = 'goalreached.mp3'
goal=0
work=0

def status_callback(msg):
    global goal, work
    for status in msg.status_list:
        if status.status == 0:  # status가 0인 경우
            print("callback Status: ", status.status)

def check_status(event):
    # 이제는 TimerEvent 인스턴스 대신에 GoalStatusArray 메시지를 사용함
    global goal, work
    msg = rospy.wait_for_message("/move_base/status", GoalStatusArray)
    for status in msg.status_list:
        if status.status == 3:  # status가 3인 경우
            print("goal reached")
            print("Status: ", status.status)
            goal += 1
            work = 0
            print(f"goal: {goal}")
            playsound(audio1)

        if status.status == 1:
            print("working")
            print("Status: ", status.status)
            goal = 0
            work += 1
            print(f"work: {work}")
            playsound(audio)


def status_subscriber():
    rospy.Subscriber("/move_base/status", GoalStatusArray, status_callback)

if __name__ == '__main__':
    try:
        rospy.init_node('ros_timer')
        status_subscriber()
        rospy.Timer(rospy.Duration(3), check_status)
        rospy.spin()

    except rospy.ROSInterruptException:
        pass
