#!/usr/bin/python3

import rospy
import time
from actionlib_msgs.msg import GoalStatusArray
from playsound import playsound

audio = 'speech.mp3'
audio1 = 'goalreached.mp3'
goal=0
work=0

def status_callback(msg):
    # 메시지를 처리하는 콜백 함수
    global goal, work
    for status in msg.status_list:
        # status_list에 있는 각 status를 처리
        if status.status == 3:  # status가 3인 경우
            print("goal reached")
            print("Status: ", status.status)
            goal=goal + 1
            work=0
            print(f"goal: {goal}")
            playsound(audio1)

        if status.status == 1 :
            print("working")
            print("Status: ", status.status)
            goal=0
            work=work + 1
            print(f"work: {work}")
            playsound(audio)
            break  # 하나만 출력하고 종료

def status_subscriber(event):
    rospy.Subscriber("/move_base/status", GoalStatusArray, status_callback)

if __name__ == '__main__':
    try:
        rospy.init_node('ros_timer')
        rospy.Timer(rospy.Duration(3), status_subscriber)
        rospy.spin()
    except rospy.ROSInterruptException:
        pass
